# bgm_list.py
TRACKS = [
    ("Amoria",          "bgm/amoria.mp3.mp3"),
    ("Aquarium",        "bgm/aquarium.mp3.mp3"),
    ("Ariant",          "bgm/ariant.mp3.mp3"),
    ("Boat Quay Town",  "bgm/boat_quay_town.mp3.mp3"),
    ("CBD",             "bgm/cbd.mp3.mp3"),
    ("Ellinia",         "bgm/ellinia.mp3.mp3"),
    ("Ellin Forest",    "bgm/ellin_forest.mp3.mp3"),
    ("El Nath",         "bgm/elnath.mp3.mp3"),
    ("Ereve",           "bgm/ereve.mp3.mp3"),
    ("Florina Beach",   "bgm/florina_beach.mp3.mp3"),
    ("Golden Temple",   "bgm/golden_temple.mp3.mp3"),
    ("Henesys",         "bgm/henesys.mp3.mp3"),
    ("Herb Town",       "bgm/herb_town.mp3.mp3"),
    ("Kampung Village", "bgm/kampung_village.mp3.mp3"),
    ("Kerning City",    "bgm/kerning_city.mp3.mp3"),
    ("Korean Folk Town","bgm/korean_folk_town.mp3.mp3"),
    ("Leafre",          "bgm/leafre.mp3.mp3"),
    ("Lith Harbor",     "bgm/lith_harbor.mp3.mp3"),
    ("Ludibrium",       "bgm/ludibrium.mp3.mp3"),
    ("Magatia",         "bgm/magatia.mp3.mp3"),
    ("Mushroom Shrine", "bgm/mushroom_shrine.mp3.mp3"),
    ("Mu Lung",         "bgm/mu_lung.mp3.mp3"),
    ("Nautilus",        "bgm/nautilus.mp3.mp3"),
    ("Omega Sector",    "bgm/omega_sector.mp3.mp3"),
    ("Orbis",           "bgm/orbis.mp3.mp3"),
    ("Perion",          "bgm/perion.mp3.mp3"),
    ("Rien",            "bgm/rien.mp3.mp3"),
    ("Shanghai",        "bgm/shanghai.mp3.mp3"),
    ("Showa Town",      "bgm/showa_town.mp3.mp3"),
    ("Sleepywood",      "bgm/sleepywood.mp3.mp3"),
    ("Temple of Time",  "bgm/temple_of_time.mp3.mp3"),
]
